### ISSUE TITLE
No longer in App Store?

### ISSUE THREAD

**Issue by nriley** [martinhering/instacast#9]
I just was transferring apps to a new iPhone 14 Pro and discovered that the app is not in the (US) App Store any more.

Is there a plan to get it back in the store or should we switch to building it from source?

(For what it's worth, I was able to build the current source with Xcode 14 and transfer my subscriptions over from my old iPhone. I changed the deployment target to iOS 11, switched to automatic signing and picked my team.)

**Comment by ibvanmat** [comment]
I made this mistake too. Never occurred to me that the app would be gone. Worse, I didn't back up my subs to a new opml file. I new the day would come where I could no longer use the app but losing 220 subs is a real bummer and there is no easy fix unless the app gets re-added to the app store so that I can restore that data from iCloud. Tried to sideload but got stuck on a provisioning error.

**Comment by nriley** [comment]
Given the number of issues with the current version on IOS 16 (most predominantly — disappearing UI, playback dropping in the background), I decided just to export my podcasts to another app.  Even if you sideloaded you wouldn't be able to get at your iCloud data I don't think; thankfully I had an older device I could use that still had the App Store Instacast on it.

I really do miss particularly the display of episode lists when compared to other podcast clients. Hoping that some new developments like https://github.com/Automattic/pocket-casts-ios will help — maybe if I get frustrated enough I'll build it myself at some point :-)

**Comment by ibvanmat** [comment]
Would that it were that simple for me. In my excitement of getting the new phone I forgot to export a new OPML file. 
I retrieved an old export from 3 years ago but it's missing about 40 subs and all the played/unplayed data since then. Not to mention the custom sort order. If i had that I would just switch to another app and make peace with it. But getting back to where I was 2 days ago where Instacast was still working for me is now impossible. Was my own undoing, sigh.

**Comment by ibvanmat** [comment]
If I only had the 6.1 Core .ipa file...
